-- ============================================
-- 个人效率工作台 - Supabase 数据库建表脚本
-- 在 Supabase 的 SQL Editor 中执行此脚本
-- ============================================

-- 1. 待办事项表
CREATE TABLE IF NOT EXISTS todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 2. 番茄钟专注记录表
CREATE TABLE IF NOT EXISTS todo_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  todo_id BIGINT REFERENCES todos(id) ON DELETE SET NULL,
  duration INTEGER NOT NULL, -- 专注时长（秒）
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 3. 日记表
CREATE TABLE IF NOT EXISTS diaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  content TEXT NOT NULL,
  images TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 4. 阅读书目表
CREATE TABLE IF NOT EXISTS reading_books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT DEFAULT '',
  cover TEXT DEFAULT '',
  status TEXT DEFAULT 'reading' CHECK (status IN ('reading', 'finished', 'wishlist')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 5. 阅读计时记录表
CREATE TABLE IF NOT EXISTS reading_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id BIGINT REFERENCES reading_books(id) ON DELETE CASCADE,
  duration INTEGER NOT NULL, -- 阅读时长（秒）
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 6. 阅读笔记表
CREATE TABLE IF NOT EXISTS reading_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id BIGINT REFERENCES reading_books(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 7. 运动记录表
CREATE TABLE IF NOT EXISTS sports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  duration INTEGER NOT NULL, -- 运动时长（分钟）
  distance REAL, -- 距离（公里）
  calories INTEGER, -- 消耗卡路里
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 8. 设置表（存储微信读书 API Key 等）
CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_todos_completed ON todos(completed);
CREATE INDEX IF NOT EXISTS idx_diaries_date ON diaries(date);
CREATE INDEX IF NOT EXISTS idx_reading_books_status ON reading_books(status);
CREATE INDEX IF NOT EXISTS idx_sports_date ON sports(date);
CREATE INDEX IF NOT EXISTS idx_sports_type ON sports(type);
CREATE INDEX IF NOT EXISTS idx_reading_sessions_book ON reading_sessions(book_id);
CREATE INDEX IF NOT EXISTS idx_reading_notes_book ON reading_notes(book_id);

-- 设置 RLS（行级安全）- 单用户应用，先放开所有权限
-- 如果你以后想加用户认证，再启用 RLS
ALTER TABLE todos ENABLE ROW LEVEL SECURITY;
ALTER TABLE todo_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE diaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_books ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE sports ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- 允许所有操作（单用户个人使用）
CREATE POLICY "Allow all" ON todos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all" ON todo_sessions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all" ON diaries FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all" ON reading_books FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all" ON reading_sessions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all" ON reading_notes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all" ON sports FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all" ON settings FOR ALL USING (true) WITH CHECK (true);
